[build]
  functions = "functions"
  # This sort of lets us build only on tagged commits to prod
  # [context.production]
  #   ignore = "if git diff $CACHED_COMMIT_REF $COMMIT_REF ./package.json | grep - | grep version && git diff $CACHED_COMMIT_REF $COMMIT_REF ./package.json | grep + | grep version; then exit 1; else exit 0; fi"

# API rewrites
[[redirects]]
  from = "/"
  to = "/.netlify/functions/ping"
  status = 200
[[redirects]]
  from = "/ping"
  to = "/.netlify/functions/ping"
  status = 200
[[redirects]]
  from = "/status/*"
  to = "/.netlify/functions/status/:splat"
  status = 200
[[redirects]]
  from = "/metrics/v2/*"
  to = "/.netlify/functions/metrics/:splat"
  status = 200
